### ISSUE TITLE
Compras: Revisar compras.

### ISSUE THREAD

**Issue by ishoussay** [ishoussay/SistemaDeGestion#11]

**Comment by ignaciolescano2001** [comment]
Revisar Compras
Monitorear solicitudes de compra:

Crear una lista donde se puedan visualizar todas las compras realizadas, organizadas por estado (pendiente, aprobada, rechazada).
Incluir detalles como fecha, usuario, monto total, productos solicitados y estado actual.
Filtrar y buscar compras:

Implementar filtros avanzados para buscar compras por estado, rango de fechas, usuarios, monto, o categoría de productos.
Auditar solicitudes:

Permitir revisar el historial de acciones asociadas a cada compra (quién creó, aprobó, o rechazó la solicitud y cuándo).
Registrar cualquier cambio o comentario durante la revisión de la compra.
Registrar observaciones:

Agregar una funcionalidad para que el revisor deje notas o comentarios sobre las compras (por ejemplo, "revisar presupuesto" o "faltan documentos").
Exportar reporte de compras:

Generar informes en formato PDF o Excel con un resumen de las compras revisadas, incluyendo métricas clave como totales por estado y montos.
