### ISSUE TITLE
Compras: Aprobar compras.

### ISSUE THREAD

**Issue by ishoussay** [ishoussay/SistemaDeGestion#12]

**Comment by ignaciolescano2001** [comment]
Revisar Compras
Monitorear solicitudes de compra:

Crear una lista donde se puedan visualizar todas las compras realizadas, organizadas por estado (pendiente, aprobada, rechazada).
Incluir detalles como fecha, usuario, monto total, productos solicitados y estado actual.
Filtrar y buscar compras:

Implementar filtros avanzados para buscar compras por estado, rango de fechas, usuarios, monto, o categoría de productos.
Auditar solicitudes:

Permitir revisar el historial de acciones asociadas a cada compra (quién creó, aprobó, o rechazó la solicitud y cuándo).
Registrar cualquier cambio o comentario durante la revisión de la compra.
Registrar observaciones:

Agregar una funcionalidad para que el revisor deje notas o comentarios sobre las compras (por ejemplo, "revisar presupuesto" o "faltan documentos").
Exportar reporte de compras:

Generar informes en formato PDF o Excel con un resumen de las compras revisadas, incluyendo métricas clave como totales por estado y montos.
Aprobar Compras
Actualizar estado de la compra:

Implementar una opción para cambiar el estado de "Pendiente" a "Aprobada" o "Rechazada".
Registrar la acción en el historial con la fecha, hora, y usuario que realizó la aprobación/rechazo.
Validar permisos de usuario:

Asegurar que solo usuarios con el rol apropiado puedan aprobar o rechazar solicitudes.
Enviar notificaciones:

Configurar notificaciones automáticas para informar al usuario solicitante cuando su compra haya sido aprobada o rechazada, indicando el motivo en caso de rechazo.
Revisar presupuesto:

Incorporar una verificación del presupuesto asignado antes de aprobar la compra para evitar excedentes.
Gestionar aprobaciones masivas:

Permitir a los usuarios aprobar múltiples solicitudes al mismo tiempo, con un resumen de los cambios realizados.
