### ISSUE TITLE
Compras: Solicitar órdenes de compra.

### ISSUE THREAD

**Issue by ishoussay** [ishoussay/SistemaDeGestion#5]

**Comment by Nahve** [comment]
---

### **Issue: Compras - Solicitar Órdenes de Compra**

**Descripción:**
Se debe implementar la funcionalidad que permita a los usuarios solicitar órdenes de compra a proveedores, seleccionando los productos que necesitan, la cantidad y el precio, así como registrar el descuento ofrecido por el proveedor. El sistema debe calcular automáticamente el total de la orden con los descuentos aplicados.

#### **Requisitos Funcionales:**

1. **Modelos:**
   - **Proveedor**: Representa a los proveedores con los que se realizarán las compras. Debe almacenar información como nombre, dirección, teléfono, correo electrónico, descuento y plazo de pago en días.
   - **OrdenCompra**: Representa una orden de compra. Debe vincularse a un proveedor y almacenar la fecha de la orden, el estado (pendiente o completado) y el total de la compra.
   - **Producto**: Almacena información sobre los productos disponibles para ser solicitados en las órdenes de compra.
   - **DetalleOrdenCompra**: Almacena los detalles de los productos dentro de una orden de compra (producto, cantidad y precio).

2. **Vista (Views):**
   - Crear una vista que permita:
     - Seleccionar un proveedor de una lista desplegable.
     - Seleccionar varios productos y definir la cantidad y precio para cada uno.
     - Registrar la orden de compra y calcular el total con el descuento aplicado por el proveedor.
     - Guardar la información de la orden y redirigir al usuario al detalle de la misma.

3. **Plantilla HTML (Frontend):**
   - Crear un formulario que permita a los usuarios:
     - Seleccionar un proveedor.
     - Añadir múltiples productos a la orden de compra, con la opción de agregar más productos dinámicamente.
     - Ingresar la cantidad y precio de cada producto.
     - Un botón para enviar el formulario y crear la orden de compra.

4. **Rutas (URLs):**
   - Definir las rutas necesarias para acceder a la vista que permite crear una orden de compra y visualizar el detalle de la orden creada.

#### **Pasos para la Implementación:**

1. **Crear los Modelos:**
   - Proveedor, OrdenCompra, Producto, y DetalleOrdenCompra, en el archivo `models.py`.
   
2. **Crear la Vista en `views.py`:**
   - Implementar la lógica para recibir el formulario, procesar los datos, calcular los descuentos y crear la orden en la base de datos.
   
3. **Crear la Plantilla HTML en `templates/compras/crear_orden_compra.html`:**
   - Diseñar un formulario dinámico que permita seleccionar proveedor, añadir productos y definir cantidades/precios.

4. **Configurar URLs en `urls.py`:**
   - Crear las rutas para acceder a la funcionalidad de creación de órdenes de compra.

#### **Detalles Técnicos:**

- Se utilizará Django como framework.
- Las órdenes de compra deben calcular el total de la compra, aplicando el descuento del proveedor a cada producto.

#### **Referencias de Código:**

- **Modelos:**

```python
# models.py
class Proveedor(models.Model):
    nombre = models.CharField(max_length=100)
    direccion = models.CharField(max_length=200)
    telefono = models.CharField(max_length=20)
    correo = models.EmailField()
    descuento = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    plazo_pago_dias = models.IntegerField(default=30)

class OrdenCompra(models.Model):
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE)
    fecha = models.DateField(auto_now_add=True)
    estado = models.CharField(max_length=20, choices=[('Pendiente', 'Pendiente'), ('Completado', 'Completado')])
    total = models.DecimalField(max_digits=10, decimal_places=2)

class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    precio = models.DecimalField(max_digits=10, decimal_places=2)

class DetalleOrdenCompra(models.Model):
    orden = models.ForeignKey(OrdenCompra, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.IntegerField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
```

- **Vista:**

```python
# views.py
from django.shortcuts import render, redirect
from .models import Proveedor, Producto, OrdenCompra, DetalleOrdenCompra

def crear_orden_compra(request):
    if request.method == 'POST':
        proveedor_id = request.POST['proveedor']
        proveedor = Proveedor.objects.get(id=proveedor_id)
        productos = request.POST.getlist('productos[]')
        cantidades = request.POST.getlist('cantidades[]')
        precios = request.POST.getlist('precios[]')

        orden = OrdenCompra.objects.create(proveedor=proveedor, estado='Pendiente', total=0)

        total_orden = 0
        for i in range(len(productos)):
            producto = Producto.objects.get(id=productos[i])
            cantidad = int(cantidades[i])
            precio = float(precios[i])
            subtotal = cantidad * precio
            subtotal_con_descuento = subtotal * (1 - proveedor.descuento / 100)
            DetalleOrdenCompra.objects.create(orden=orden, producto=producto, cantidad=cantidad, precio=precio)
            total_orden += subtotal_con_descuento

        orden.total = total_orden
        orden.save()

        return redirect('orden_compra_detalle', orden_id=orden.id)

    else:
        proveedores = Proveedor.objects.all()
        productos = Producto.objects.all()
        return render(request, 'compras/crear_orden_compra.html', {'proveedores': proveedores, 'productos': productos})
```

- **Plantilla HTML:**

```html
<form method="POST" action="{% url 'crear_orden_compra' %}">
  {% csrf_token %}
  
  <div class="form-group">
    <label for="proveedor">Proveedor:</label>
    <select name="proveedor" id="proveedor" class="form-control">
      {% for proveedor in proveedores %}
        <option value="{{ proveedor.id }}">{{ proveedor.nombre }} - Descuento: {{ proveedor.descuento }}%</option>
      {% endfor %}
    </select>
  </div>

  <div class="form-group">
    <label for="productos">Productos:</label>
    <div id="productos-container">
      <div class="producto-item">
        <select name="productos[]" class="form-control">
          {% for producto in productos %}
            <option value="{{ producto.id }}">{{ producto.nombre }}</option>
          {% endfor %}
        </select>
        <input type="number" name="cantidades[]" placeholder="Cantidad" class="form-control" required>
        <input type="number" name="precios[]" placeholder="Precio" class="form-control" step="0.01" required>
      </div>
    </div>
    <button type="button" id="add-producto" class="btn btn-secondary">Agregar Producto</button>
  </div>

  <button type="submit" class="btn btn-primary">Crear Orden de Compra</button>
</form>

<script>
  document.getElementById('add-producto').addEventListener('click', function() {
    const container = document.getElementById('productos-container');
    const newProducto = document.querySelector('.producto-item').cloneNode(true);
    container.appendChild(newProducto);
  });
</script>
```

#### **Tareas:**
- [ ] Crear los modelos `Proveedor`, `OrdenCompra`, `Producto`, y `DetalleOrdenCompra`.
- [ ] Implementar la vista para la creación de órdenes de compra.
- [ ] Crear la plantilla HTML con formulario dinámico para añadir productos.
- [ ] Configurar las URLs correspondientes.

---
