### ISSUE TITLE
Compras: Negociar con proveedores.

### ISSUE THREAD

**Issue by ishoussay** [ishoussay/SistemaDeGestion#6]

**Comment by Nahve** [comment]
## Estructura del Proyecto - Compras: Negociar con Proveedores


### Proyecto Completo

```bash
proyecto/
│
├── compras/                   # App "compras"
│   ├── migrations/            # Migraciones de la base de datos
│   │   └── __init__.py
│   │
│   ├── templates/             # Plantillas HTML
│   │   └── compras/           
│   │       ├── crear_orden_compra.html    # Formulario para crear orden de compra
│   │       ├── negociar_proveedor.html    # Formulario para negociar con proveedores
│   │       └── historial_negociaciones.html  # Historial de negociaciones
│   │
│   ├── static/                # Archivos estáticos (CSS, JS)
│   │   └── compras/           
│   │       ├── css/           # Estilos
│   │       │   └── estilos.css
│   │       └── js/            # Scripts
│   │           └── dinamico.js   # Lógica de frontend
│   │
│   ├── admin.py               # Registro de modelos para el admin de Django
│   ├── apps.py                # Configuración de la app
│   ├── models.py              # Modelos
│   ├── views.py               # Vistas
│   ├── urls.py                # Rutas de la app
│   ├── forms.py               # Formularios de Django (opcional)
│   └── __init__.py
│
├── proyecto/                  # Configuración principal del proyecto
│   ├── __init__.py
│   ├── settings.py            # Configuración del proyecto
│   ├── urls.py                # Rutas principales
│   ├── wsgi.py                # Configuración para despliegue
│   └── asgi.py                # Configuración para despliegue (ASGI)
│
├── manage.py                  # Script de Django
└── requirements.txt           # Dependencias
```

---

### Descripción de Carpetas y Archivos

#### 1. **`compras/`**:
- **Descripción**: Esta carpeta contiene la lógica específica de la app "compras", donde se gestionan las órdenes de compra y las negociaciones con proveedores.
  - **`migrations/`**: 
    - **`__init__.py`**: Archivo que inicializa las migraciones de la base de datos de la app "compras".
  
  - **`templates/`**: 
    - **Descripción**: Contiene las plantillas HTML utilizadas para generar las interfaces de usuario.
    - **`crear_orden_compra.html`**: Formulario para la creación de órdenes de compra.
    - **`negociar_proveedor.html`**: Formulario para registrar una negociación con un proveedor, como descuentos y plazos de pago.
    - **`historial_negociaciones.html`**: Página que muestra el historial de negociaciones realizadas con los proveedores.

  - **`static/`**:
    - **Descripción**: Archivos estáticos como CSS y JS.
    - **`css/estilos.css`**: Archivo de estilos personalizados para la app "compras", aplicados a las plantillas HTML.
    - **`js/dinamico.js`**: Contiene la lógica del frontend para gestionar dinámicamente la página, como agregar o eliminar elementos en formularios de forma interactiva.
  
  - **`admin.py`**:
    - **Descripción**: Registra los modelos de la app "compras" en el panel de administración de Django. Aquí se puede configurar qué modelos serán visibles y editables desde el admin.
  
  - **`apps.py`**:
    - **Descripción**: Archivo que contiene la configuración de la app "compras". Es generado automáticamente por Django y registra la app en el proyecto general.
  
  - **`models.py`**:
    - **Descripción**: Define los modelos de datos que representan las entidades del sistema, como las negociaciones con proveedores o las órdenes de compra.
  
  - **`views.py`**:
    - **Descripción**: Contiene la lógica de las vistas, que gestionan las solicitudes del usuario, recuperan datos de los modelos y renderizan las plantillas HTML.
  
  - **`urls.py`**:
    - **Descripción**: Define las rutas (URLs) de la app "compras". Cada ruta corresponde a una vista que responde a una solicitud del navegador.
  
  - **`forms.py`** (Opcional):
    - **Descripción**: Si se utilizan formularios personalizados en Django, este archivo define la estructura y validación de esos formularios.

#### 2. **`proyecto/`**:
- **Descripción**: Configuración general del proyecto Django.
  - **`__init__.py`**: Inicializa el paquete de configuración del proyecto.
  
  - **`settings.py`**:
    - **Descripción**: Contiene la configuración principal del proyecto Django, como la base de datos, las aplicaciones instaladas, configuraciones de middleware y archivos estáticos.
  
  - **`urls.py`**:
    - **Descripción**: Define las rutas principales del proyecto. Aquí se incluyen las rutas de las diferentes aplicaciones, como la app "compras".
  
  - **`wsgi.py`**:
    - **Descripción**: Archivo de configuración utilizado para el despliegue del proyecto Django en servidores que soportan WSGI (Web Server Gateway Interface).
  
  - **`asgi.py`**:
    - **Descripción**: Archivo de configuración utilizado para despliegue en servidores que soportan ASGI (Asynchronous Server Gateway Interface), útil para manejar websockets u otras funcionalidades asincrónicas.

#### 3. **`manage.py`**:
- **Descripción**: Script principal que permite ejecutar comandos relacionados con la gestión del proyecto Django, como realizar migraciones, ejecutar el servidor local o crear superusuarios.

#### 4. **`requirements.txt`**:
- **Descripción**: Lista de las dependencias necesarias para ejecutar el proyecto. Aquí se definen las versiones de las bibliotecas externas necesarias para que el proyecto funcione correctamente, como Django u otras librerías adicionales.

---

### Notas:
- Esta estructura está diseñada siguiendo las buenas prácticas de Django, separando la lógica del negocio, las vistas, las plantillas y los archivos estáticos.
- La carpeta `migrations/` es gestionada automáticamente por Django, y es fundamental para la actualización de los modelos en la base de datos.
- Se recomienda utilizar la carpeta `static/` para almacenar los archivos que no cambian con frecuencia (CSS, JS, imágenes).
- Las plantillas HTML están separadas por funcionalidad para facilitar el mantenimiento y evitar duplicación de código.
```
